<?php
/**Generate by ASGENS
 * @author Amanda
 * @date Fri May 31 07:56:17 GMT-04:00 2024
 * @time Fri May 31 07:56:17 GMT-04:00 2024
 */


namespace Modules\admin\Models;


use App\Models\BaseModel;
use App\Scopes\NonDeletedScope;
use Exception;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Facades\Storage;
use Modules\admin\Observers\ImageInsertObserver;
use Modules\nomenclature\Models\Category;
use Modules\nomenclature\Models\UnitMeasurement;
use Modules\stocktaking\Models\Invoice_product;
use Modules\stocktaking\Models\Warehouse_product;

/**
 * Este es la clase modelo para la tabla admin.products.
 *
 * Los siguientes son los campos de la tabla 'admin.products':
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property string $image
 * @property integer $category_id
 * @property integer $unit_id
 *
 * Los siguientes son las relaciones de este modelo :
 * @property Category $category
 * @property UnitMeasurement $unit
 * @property Provider_product[] $array_provider_product
 * @property Provider[] $array_provider
 **/
#[ObservedBy([ImageInsertObserver::class])]
class Product extends BaseModel
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'admin.products';

    /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = true;

    public $hidden = ['created_at', 'updated_at'];


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['category', 'array_provider_product', 'array_provider'];

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = ['image_url'];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Product';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'code',
        'image',
        'category_id',
        'unit_id'
    ];

    /**
     * Get the category
     */
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    /**
     * Get the Unit
     */
    public function unit()
    {
        return $this->belongsTo(UnitMeasurement::class, 'unit_id', 'id');
    }


    /**
     *
     * Get array_provider_product
     */
    public function array_provider_product()
    {
        return $this->hasMany(Provider_product::class, 'product_id', 'id');
    }

    /**
     *
     * Get invoice_products
     */
    public function invoice_products()
    {
        return $this->hasOne(Invoice_product::class, 'product_id', 'id');
    }


    /* Many to many relationships */


    /**
     *
     * Get array_provider
     */
    /**
     * @return BelongsToMany of Provider
     */
    public function array_provider()
    {
        return $this->belongsToMany(Provider::class, 'provider_product', 'product_id', 'provider_id')
            ->as('provider_product')
            ->withPivot(Provider_product::columns)
            ->withGlobalScope('non_deleted', new NonDeletedScope());
    }

    public function getImageUrlAttribute()
    {
        return Storage::disk('public')->url($this->image);
    }


    protected function rules($scenario = 'create')
    {
        $rules = include(__DIR__ . '/../Rules/ProductRule.php');
        if (!isset($rules[$scenario]))
            throw new Exception('Scenario ' . $scenario . ' not exist');
        return $rules[$scenario];
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function (Product $model) {
            Warehouse_product::create([
                'product_id' => $model->id,
                'quantity' => 0,
            ]);
        });
    }
}

