<?php
/**Generate by ASGENS
 * @author Amanda
 * @date Fri May 31 07:56:17 GMT-04:00 2024
 * @time Fri May 31 07:56:17 GMT-04:00 2024
 */


namespace Modules\admin\Models;


use App\Models\BaseModel;

use Exception;
use App\Scopes\NonDeletedScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * Este es la clase modelo para la tabla admin.providers.
 *
 * Los siguientes son los campos de la tabla 'admin.providers':
 * @property integer $id
 * @property string $name
 * @property string $identification
 * @property string $phone
 * @property string $email
 * @property string $country
 * @property string $city
 * @property string $classification
 * @property string $fax
 * @property string $observations
 * @property string $address
 * @property string $postal_code
 *
 * Los siguientes son las relaciones de este modelo :
 * @property Provider_product[] $array_provider_product
 * @property Products_view[] $array_products
 * @property Provider_contact[] $array_contacts
 **/
class Provider extends BaseModel
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'admin.providers';

    /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = true;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_provider_product', 'array_products', 'array_contacts'];

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    protected $hidden = ['updated_at', 'created_at'];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Provider';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'identification',
        'phone',
        'email',
        'country',
        'city',
        'classification',
        'fax',
        'observations',
        'address',
        'postal_code',
        'updated_at'
    ];


    /**
     *
     * Get array_provider_product
     */
    public function array_provider_product()
    {
        return $this->hasMany(Provider_product::class, 'provider_id', 'id');
    }


    /**
     *
     * Get array_contacts
     */
    public function array_contacts()
    {
        return $this->hasMany(Provider_contact::class, 'provider_id', 'id');
    }


    /* Many to many relationships */


    /**
     *
     * Get array_product
     */
    public function array_products()
    {
        return $this->hasMany(Products_view::class, 'provider_id', 'id');
    }


    protected function rules($scenario = 'create')
    {
        $rules = include(__DIR__ . '/../Rules/ProviderRule.php');
        if (!isset($rules[$scenario]))
            throw new Exception('Scenario ' . $scenario . ' not exist');
        return $rules[$scenario];
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function (Provider $model) {
            $model->array_contacts()->createMany(request()->get('array_contacts'));
            $model->array_provider_product()->createMany(request()->get('array_products'));
        });
        static::updated(function (Provider $model) {
            //contacts
            $contacts = request()->get('array_contacts');
            $contacts_ids = collect($contacts)->whereNotNull('id')->map(fn($item) => $item['id'])->toArray();
            $model->array_contacts()->whereNotIn('id', $contacts_ids)->delete();
            foreach ($contacts as $contact) {
                $contact_id = $contact['id'] ?? null;
                $model->array_contacts()->updateOrCreate(['id' => $contact_id], $contact);
            }
            //products
            $products = request()->get('array_products');
            $product_ids = collect($products)->whereNotNull('id')->map(fn($item) => $item['id'])->toArray();
            $model->array_provider_product()->whereNotIn('id', $product_ids)->delete();
            foreach ($products as $product) {
                $product_id = $product['id'] ?? null;
                $model->array_provider_product()->updateOrCreate(['id' => $product_id], $product);
            }
        });
    }

}

