<?php
/**Generate by ASGENS
 * @author Amanda
 * @date Fri May 31 07:56:17 GMT-04:00 2024
 * @time Fri May 31 07:56:17 GMT-04:00 2024
 */


namespace Modules\admin\Models;


use App\Helpers\Utils;
use App\Models\BaseModel;
use Exception;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Support\Facades\Storage;
use Modules\admin\Observers\ImageInsertObserver;
use Modules\security\Models\User;

/**
 * Este es la clase modelo para la tabla admin.workers.
 *
 * Los siguientes son los campos de la tabla 'admin.workers':
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property string $image
 * @property string $phone
 * @property string $lastname
 *
 *
 * Los siguientes son las relaciones de este modelo :
 * @property Worker_area_turn[] $array_area_turn
 * @property Area[] $array_area
 * @property User $user
 **/
#[ObservedBy([ImageInsertObserver::class])]
class Worker extends BaseModel

{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'admin.workers';

    /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = true;

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['image', 'area_id', 'turn_id', 'role_id', 'created_at', 'updated_at'];

    const RELATIONS = ['array_area', 'user'];

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = ['image_url'];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Worker';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'image',
        'phone',
        'lastname',
        'user_id',
        'updated_at'
    ];


    /**
     *
     * Get user
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }


    /**
     *
     * Get array_worker_area_turn
     */
    public function array_area_turn()
    {
        return $this->hasMany(Worker_area_turn::class, 'worker_id', 'id');
    }


    /* Many to many relationships */

    protected function rules($scenario = 'create')
    {
        $rules = include(__DIR__ . '/../Rules/WorkerRule.php');
        if (!isset($rules[$scenario]))
            throw new Exception('Scenario ' . $scenario . ' not exist');
        return $rules[$scenario];
    }

    public function getImageUrlAttribute()
    {
        return Storage::disk('public')->url($this->image);
    }

    private static function transform_array($array)
    {
        return collect($array)->map(function ($item) {
            return [
                'id' => $item['id'] ?? null,
                'area_id' => $item['area']['id'],
                'turn_id' => $item['turn']['id']
            ];
        })->toArray();
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $array_area_turn = Utils::json_to_string(request()->get('array_area_turn'));

        static::creating(function (Worker $model) {
            //create user
            $user = $model->user()->create(request()->only(['username', 'email', 'password']));
            $model->user_id = $user->id;
        });

        static::created(function (Worker $model) use ($array_area_turn) {
            //create area_turn
            $objects = self::transform_array($array_area_turn);
            $model->array_area_turn()->createMany($objects);
        });

        static::updating(function (Worker $model) {
            //update user
            $model->user()->update(request()->only(['username', 'email', 'password', 'updated_at']));
            $model->user->touch();
        });

        static::updated(function (Worker $model) use ($array_area_turn) {
            // update, create o delete area_turn
            $objects = self::transform_array($array_area_turn);
            $area_turn_ids = collect($objects)->whereNotNull('id')->map(fn($item) => $item['id'])->toArray();
            $model->array_area_turn()->whereNotIn('id', $area_turn_ids)->delete();
            foreach ($objects as $area_turn) {
                $area_turn['worker_id'] = $model->id;
                $model->array_area_turn()->updateOrCreate(['id' => $area_turn['id']], $area_turn);
            }
        });

        static::deleting(function (Worker $model) {
            $model->user()->delete();
        });
    }
}