<?php
/**Generate by ASGENS
 * @author Amanda
 * @date Wed Nov 06 10:55:40 GMT-05:00 2024
 * @time Wed Nov 06 10:55:40 GMT-05:00 2024
 */


namespace Modules\restaurant\Models;


use App\Models\BaseModel;

use Exception;
use App\Scopes\NonDeletedScope;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Carbon;

/**
 * Este es la clase modelo para la tabla restaurant.menu.
 *
 * Los siguientes son los campos de la tabla 'restaurant.menu':
 * @property integer $id
 * @property Carbon $date
 * @property string $meal_type
 *
 * Los siguientes son las relaciones de este modelo :
 * @property Menu_offers[] $array_menu_offers
 * @property Offer[] $array_offer
 **/
class Menu extends BaseModel
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'restaurant.menu';

    /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_menu_offers', 'array_offers'];

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Menu';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'date',
        'meal_type'
    ];


    /**
     *
     * Get array_menu_offers
     */
    public function array_menu_offers()
    {
        return $this->hasMany(Menu_offers::class, 'menu_id', 'id');
    }


    /* Many to many relationships */


    /**
     *
     * Get array_offer
     */
    /**
     * @return BelongsToMany of Offer
     */
    public function array_offers()
    {
        return $this->belongsToMany(Offer::class, 'restaurant.menu_offers', 'menu_id', 'offer_id')
            ->as('menu_offers')
            ->withPivot(Menu_offers::columns)
            ->withGlobalScope('non_deleted', new NonDeletedScope());
    }


    protected function rules($scenario = 'create')
    {
        $rules = include(__DIR__ . '/../Rules/MenuRule.php');
        if (!isset($rules[$scenario]))
            throw new Exception('Scenario ' . $scenario . ' not exist');
        return $rules[$scenario];
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $offers = request()->get('array_offers');

        static::creating(function (Menu $model) {
            $model->date = request()->get('date') ? request()->get('date') : Carbon::now();
        });

        static::created(function (Menu $model) use ($offers) {
            $model->array_menu_offers()->createMany($offers);
        });

        static::updated(function (Menu $model) use ($offers) {
            $offer_ids = collect($offers)->whereNotNull('id')->map(fn($item) => $item['id'])->toArray();
            $model->array_menu_offers()->whereNotIn('offer_id', $offer_ids)->delete();
            foreach ($offers as $offer) {
                $offer_id = $offer['id'] ?? null;
                $model->array_menu_offers()->updateOrCreate(['offer_id' => $offer_id], $offer);
            }
        });
    }

}

