<?php
/**Generate by ASGENS
 * @author Amanda
 * @date Wed Nov 06 10:55:40 GMT-05:00 2024
 * @time Wed Nov 06 10:55:40 GMT-05:00 2024
 */


namespace Modules\restaurant\Models;


use App\Helpers\Utils;
use App\Models\BaseModel;
use App\Scopes\NonDeletedScope;
use Exception;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Facades\Storage;
use Modules\admin\Models\Product;
use Modules\admin\Observers\ImageInsertObserver;
use Modules\stocktaking\Models\Order;
use Modules\stocktaking\Models\Order_product;

/**
 * Este es la clase modelo para la tabla restaurant.offers.
 *
 * Los siguientes son los campos de la tabla 'restaurant.offers':
 * @property integer $id
 * @property string $name
 * @property integer $price
 * @property string $image
 * @property string $description
 *
 * Los siguientes son las relaciones de este modelo :
 * @property Menu_offers[] $array_menu_offers
 * @property Menu[] $array_menu
 * @property Offer_products[] $array_offer_products
 * @property Product[] $array_products
 * @property Order_product[] $array_order_products
 * @property Order[] $array_order
 **/
#[ObservedBy([ImageInsertObserver::class])]
class Offer extends BaseModel
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'restaurant.offers';

    /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = true;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_menu_offers', 'array_offer_products', 'array_order_products', 'array_menu', 'array_products', 'array_orders'];

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = ['image_url'];

    protected $hidden = ['created_at', 'updated_at'];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Offer';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'price',
        'image',
        'description',
        'updated_at'
    ];

    protected $casts = [
        'price' => 'float'
    ];


    /**
     *
     * Get array_menu_offers
     */
    public function array_menu_offers()
    {
        return $this->hasMany(Menu_offers::class, 'offer_id', 'id');
    }

    /**
     *
     * Get array_offer_products
     */
    public function array_offer_products()
    {
        return $this->hasMany(Offer_products::class, 'offer_id', 'id');
    }

    /**
     *
     * Get array_order_products
     */
    public function array_order_products()
    {
        return $this->hasMany(Order_product::class, 'offer_id', 'id');
    }


    /* Many to many relationships */


    /**
     *
     * Get array_menu
     */
    /**
     * @return BelongsToMany of Menu
     */
    public function array_menu()
    {
        return $this->belongsToMany(Menu::class, 'menu_offers', 'offer_id', 'menu_id')
            ->as('menu_offers')
            ->withPivot(Menu_offers::columns)
            ->withGlobalScope('non_deleted', new NonDeletedScope());
    }

    /**
     *
     * Get array_product
     */
    public function array_products()
    {
        return $this->hasMany(Offer_products_view::class, 'offer_id', 'id');
    }

    /**
     *
     * Get array_order
     */
    /**
     * @return BelongsToMany of Orders
     */
    public function array_order()
    {
        return $this->belongsToMany(Order::class, 'order_products', 'offer_id', 'order_id')
            ->as('order_products')
            ->withPivot(Order_product::columns)
            ->withGlobalScope('non_deleted', new NonDeletedScope());
    }


    public function getImageUrlAttribute()
    {
        return Storage::disk('public')->url($this->image);
    }


    protected function rules($scenario = 'create')
    {
        $rules = include(__DIR__ . '/../Rules/OfferRule.php');
        if (!isset($rules[$scenario]))
            throw new Exception('Scenario ' . $scenario . ' not exist');
        return $rules[$scenario];
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $products = Utils::json_to_string(request()->get('array_products'));

        static::created(function (Offer $model) use ($products) {
            $model->array_offer_products()->createMany($products);
        });

        static::updated(function (Offer $model) use ($products) {
            $product_ids = collect($products)->whereNotNull('product_id')->map(fn($item) => $item['product_id'])->toArray();
            $model->array_offer_products()->whereNotIn('product_id', $product_ids)->delete();
            foreach ($products as $product) {
                $product_id = $product['product_id'] ?? null;
                $model->array_offer_products()->updateOrCreate(['product_id' => $product_id], $product);
            }
        });
    }

}

