<?php
/**Generate by ASGENS
 * @author Amanda
 * @date Fri May 31 07:56:17 GMT-04:00 2024
 * @time Fri May 31 07:56:17 GMT-04:00 2024
 */


namespace Modules\security\Models;


use App\Models\BaseModel;

use Exception;
use App\Scopes\NonDeletedScope;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * Este es la clase modelo para la tabla security.roles.
 *
 * Los siguientes son los campos de la tabla 'security.roles':
 * @property integer $id
 * @property string $name
 * @property string $description
 *
 * Los siguientes son las relaciones de este modelo :
 * @property Role_permissions[] $array_role_permissions
 * @property Permission[] $array_permissions
 * @property Role_user[] $array_role_users
 * @property User[] $array_user
 * */
class Role extends BaseModel
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'security.roles';

    /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = true;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_role_permissions', 'array_role_users', 'array_permissions', 'array_users'];


    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Role';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description'
    ];

    /**
     *
     * Get array_role_users
     */
    public function array_role_users()
    {
        return $this->hasMany(Role_user::class, 'role_id', 'id');
    }


    /**
     *
     * Get array_role_permissions
     */
    public function array_role_permissions()
    {
        return $this->hasMany(Role_permissions::class, 'role_id', 'id');
    }


    /* Many to many relationships */

    /**
     *
     * Get array_permission
     */
    /**
     * @return BelongsToMany of Permission
     */
    public function array_permissions()
    {
        return $this->belongsToMany(Permission::class, 'security.role_permissions', 'role_id', 'permission_id')
            ->as('role_permissions')
            ->withPivot(Role_permissions::columns)
            ->withGlobalScope('non_deleted', new NonDeletedScope());
    }

    /**
     *
     * Get array_user
     */
    /**
     * @return BelongsToMany of Users
     */
    public function array_user()
    {
        return $this->belongsToMany(User::class, 'security.role_users', 'role_id', 'user_id')
            ->as('role_users')
            ->withPivot(Role_user::columns)
            ->withGlobalScope('non_deleted', new NonDeletedScope());
    }


    protected function rules($scenario = 'create')
    {
        $rules = include(__DIR__ . '/../Rules/RoleRule.php');
        if (!isset($rules[$scenario]))
            throw new Exception('Scenario ' . $scenario . ' not exist');
        return $rules[$scenario];
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $array_permissions = request()->get('array_permissions');

        static::created(function (Role $model) use ($array_permissions) {
            //roles
            $model->array_permissions()->attach($array_permissions);
        });

        static::updating(function (Role $model) use ($array_permissions) {
            $model->array_role_permissions()->whereNotIn('permission_id', $array_permissions)->delete();
            foreach ($array_permissions as $permission) {
                $model->array_role_permissions()->updateOrCreate(['permission_id' => $permission]);
            }
        });
    }

}

