<?php
/**Generate by ASGENS
 * @author amanda
 * @date Sat Oct 05 18:46:52 GMT-04:00 2024
 * @time Sat Oct 05 18:46:52 GMT-04:00 2024
 */


namespace Modules\stocktaking\Models;


use App\Models\BaseModel;

use Exception;
use App\Scopes\NonDeletedScope;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Modules\admin\Models\Client;
use Modules\admin\Models\Product;
use Illuminate\Support\Carbon;

/**
 * Este es la clase modelo para la tabla stocktaking.orders.
 *
 * Los siguientes son los campos de la tabla 'stocktaking.orders':
 * @property integer $id
 * @property integer $total_amount
 * @property Carbon $date
 * @property string $type_payment
 * @property boolean $is_delivery
 * @property integer $delivery_amount
 * @property integer $client_id
 * @property string $status
 * @property string $created_in
 *
 * Los siguientes son las relaciones de este modelo :
 * @property Client $client
 * @property Order_product[] $array_order_products
 * @property Order_offers_view[] $array_products
 **/
class Order extends BaseModel
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'stocktaking.orders';

    /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['client', 'array_order_products', 'array_products'];

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Order';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'total_amount',
        'date',
        'type_payment',
        'is_delivery',
        'delivery_amount',
        'client_id',
        'status',
        'created_in'
    ];

    /**
     * Get the client
     */
    public function client()
    {
        return $this->belongsTo(Client::class, 'client_id', 'id');
    }


    /**
     *
     * Get array_order_products
     */
    public function array_order_offers()
    {
        return $this->hasMany(Order_product::class, 'order_id', 'id');
    }


    /* Many to many relationships */


    /**
     *
     * Get array_products
     */
    public function array_offers()
    {
        return $this->hasMany(Order_offers_view::class, 'order_id', 'id');
    }


    protected function rules($scenario = 'create')
    {
        $rules = include(__DIR__ . '/../Rules/OrderRule.php');
        if (!isset($rules[$scenario]))
            throw new Exception('Scenario ' . $scenario . ' not exist');
        return $rules[$scenario];
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $offers = request()->get('array_offers');

        static::creating(function (Order $model) {
            $model->status = "en proceso";
            $model->delivery_amount = request()->get('is_delivery') ? request()->get('delivery_amount') : null;
            $model->date = request()->get('date') ? request()->get('date') : Carbon::now();

            //client
            if (request()->get('created_in') === 'shopping') {
                $data_client = request()->get('client');
                $client = Client::query()->where('name', $data_client['name'])
                    ->where('phone', $data_client['phone'])->first();
                if ($client)
                    $model->client_id = $client->id;
                else {
                    $client = Client::create($data_client);
                    $model->client_id = $client->id;
                }
            }
        });

        static::created(function (Order $model) use ($offers) {
            $model->array_order_offers()->createMany(
                collect($offers)->map(fn($offer) => [
                    'offer_id' => $offer['id'] ?? $offer['offer_id'],
                    'quantity' => $offer['quantity']
                ])
            );
        });

        static::updating(function (Order $model) {
            $model->delivery_amount = request()->get('is_delivery') ? request()->get('delivery_amount') : null;
        });

        static::updated(function (Order $model) use ($offers) {
            $offer_ids = collect($offers)->whereNotNull('offer_id')->map(fn($item) => $item['offer_id'])->toArray();
            $model->array_order_offers()->whereNotIn('offer_id', $offer_ids)->delete();
            foreach ($offers as $offer) {
                $offer_id = $offer['offer_id'] ?? null;
                $model->array_order_offers()->updateOrCreate(['offer_id' => $offer_id], $offer);
            }
        });
    }
}

