<?php
/**Generate by ASGENS
 * @author amanda
 * @date Sat Oct 05 18:46:52 GMT-04:00 2024
 * @time Sat Oct 05 18:46:52 GMT-04:00 2024
 */


namespace Modules\stocktaking\Models;


use App\Helpers\Utils;
use App\Models\BaseModel;
use Exception;
use Illuminate\Support\Carbon;
use Modules\admin\Models\Worker;
use Modules\security\Models\User;

/**
 * Este es la clase modelo para la tabla stocktaking.requests.
 *
 * Los siguientes son los campos de la tabla 'stocktaking.requests':
 * @property integer $id
 * @property integer $worker_id
 * @property string $description
 * @property string $status
 * @property Carbon $date
 * @property integer $cancelled_by
 *
 * Los siguientes son las relaciones de este modelo :
 * @property Worker $worker
 * @property Worker $worker_cancel
 * @property Request_product[] $array_request_products
 **/
class Request extends BaseModel
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'stocktaking.requests';

    /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['worker', 'array_request_products', 'worker_cancel'];

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Request';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'worker_id',
        'cancelled_by',
        'description',
        'status',
        'date'
    ];

    /**
     * Get the worker
     */
    public function worker()
    {
        return $this->belongsTo(Worker::class, 'worker_id', 'id');
    }

    /**
     * Get the cancelled_by
     */
    public function worker_cancel()
    {
        return $this->belongsTo(Worker::class, 'cancelled_by', 'id');
    }


    /**
     *
     * Get array_request_products
     */
    public function array_request_products()
    {
        return $this->hasMany(Request_product::class, 'request_id', 'id');
    }

    /**
     *
     * Get array_product
     */
    public function array_products()
    {
        return $this->hasMany(Request_products_view::class, 'request_id', 'id');
    }


    /* Many to many relationships */


    protected function rules($scenario = 'create')
    {
        $rules = include(__DIR__ . '/../Rules/RequestRule.php');
        if (!isset($rules[$scenario]))
            throw new Exception('Scenario ' . $scenario . ' not exist');
        return $rules[$scenario];
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $products = request()->get('array_products');

        static::creating(function (Request $model) {
            $model->status = "pendiente";
            $model->date = request()->get('date') ? request()->get('date') : Carbon::now();
        });

        static::created(function (Request $model) use ($products) {
            $model->array_request_products()->createMany($products);
        });

        static::updating(function (Request $model) {
            $status = $model->status;
            $status_before = $model->getOriginal('status');

            if ($model->status === 'aprobada' && $status_before === 'pendiente') {
                Utils::increment_decrement_quantity_warehouse($model, 'decrement');
            } elseif ($status === 'cancelada' && $status_before === 'aprobada') {
                Utils::increment_decrement_quantity_warehouse($model, 'increment');
            }
        });

        static::updated(function (Request $model) use ($products) {
            //products
            if (!$model->isDirty('status')) {
                $product_ids = collect($products)->whereNotNull('id')->map(fn($item) => $item['id'])->toArray();
                $model->array_request_products()->whereNotIn('id', $product_ids)->delete();
                foreach ($products as $product) {
                    $product_id = $product['id'] ?? null;
                    $model->array_request_products()->updateOrCreate(['id' => $product_id], $product);
                }
            }
        });
    }
}

