<?php


/**Generate by ASGENS
*@author Amanda  
*@date Fri May 31 07:56:16 GMT-04:00 2024  
*@time Fri May 31 07:56:16 GMT-04:00 2024  
*/


namespace App\Models;


use App\Scopes\NonDeletedScope;

class BaseModel extends \Ronu\RestGenericClass\Core\Models\BaseModel
{
    public function __construct(array $attributes = []){
        parent::__construct($attributes);
    }

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope('non_deleted',new NonDeletedScope());
    }
}
